assume_extension: true
check_img_alt: false
only_4xx: true
http_status_ignore:
  - 429
  - 403
  - 400
url_ignore:
  - /http:\/\/www.gutenberg.org\/.*?/
  - /https:\/\/github.com\/programminghistorian\/.*?/
  - /https:\/\/github.com\/orgs\/programminghistorian\/.*?/
  - /\#/
  - /espanol/
  - /deprecated/
  - /collection.britishmuseum.org/
  - /analytics.hathitrust.org/
  - /fr.wikipedia.org\/wiki/
  - /https:\/\/web.archive.org\/web\/20180831094856\/http:\/\/www.dlsi.ua.es\/~borja\/riilua\/6.TopicModeling_v02.pdf/
directory_ignore:
  - /assets/
  - /retired/
  - /retirada/
  - /retrait/
  - /posts/