assume_extension: true
only_4xx: true
ignore_missing_alt: true
ignore_empty_alt: true
allow_hash_href: true
check_external_hash: false
http_status_ignore:
  - 429
  - 403
  - 400
url_ignore:
  - /\/\/www.gutenberg.org\/.*?/
  - /https:\/\/github.com\/programminghistorian\/.*?/
  - /https:\/\/github.com\/orgs\/programminghistorian\/.*?/
  - /\#/
  - /espanol/
  - /deprecated/
  - /collection.britishmuseum.org/
  - /analytics.hathitrust.org/
  - /fr.wikipedia.org\/wiki/
  - /https:\/\/web.archive.org\/web\/20180831094856\/http:\/\/www.dlsi.ua.es\/~borja\/riilua\/6.TopicModeling_v02.pdf/
  - https://github.com/programminghistorian/jekyll/commits/gh-pages
  - https://github.com/programminghistorian/jekyll/commits/gh-pages/.*
directory_ignore:
  - assets
  - retired
  - retirada
  - retrait
  - posts
ignore_elements:
  - pre
  - code
  - script
typhoeus:
  connecttimeout: 30
  timeout: 60
  max_concurrency: 2
log_level: debug